spring.profiles.active=dev
server.port=8080

spring.application.name=management

# SQL Server local connection
spring.datasource.url=jdbc:mysql://localhost:3306/StudentDormitoryManagement?serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Consistent JSON date-time format
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss

# Enable static resource mappings (default behavior)
spring.web.resources.add-mappings=true

app.jwt.secret=Z3V5ZW5fdmFuX2FfMTIzNDU2Nzg5X2JjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=
app.jwt.expiration-ms=86400000